# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bwa6rFSaI7bDi7IZl0sHmvsCCnr_ORim
"""

num = int(input("Ate que numero voce quer saber quais são primos"))
listanum = []
for i in range(num):
  if i % 2 != 0:
    cont = 0
    for c in range(1,10):      
      divisao = i % c
      if divisao == 0:
        cont += 1
    if cont <= 2:
      print (i)
      listanum.append(i)
print (f'Existe {len(listanum)} números primos até o número {num}')